### ISSUE TITLE
Не отображается контент не некоторых масштабах

### ISSUE THREAD

**Issue by adubovskoy** [dru-io/drupal.dru.io#11]
https://files.gitter.im/dru-io/Dru.io/2xLe/Video_2017-09-14_175555.wmv

промо при масштабе 125%

tnx @xandeadx за багрепорт

**Comment by Niklan** [comment]
У меня всё ок при масштабе 125%

**Comment by alexd73** [comment]
Привет! Зметил подобное при ширине больше 1180 на Chromium Version 61.0.3163.91 (Developer Build) (64-bit) и Vivaldi | 1.12.955.36 (Stable channel) (64-bit)
