### ISSUE TITLE
Деформирован favicon

### ISSUE THREAD

**Issue by KhabibullinMax** [dru-io/drupal.dru.io#2]
Немного сплюснут по вертикали, из-за размеров лого 68px на 79px

**Comment by KhabibullinMax** [comment]
![drupal-logo-2_0](https://user-images.githubusercontent.com/5961634/28812870-35257066-76b0-11e7-8e40-dcd6378e06ef.png)

**Comment by Niklan** [comment]
Спасибо, поменял.
